version: '1.0.0'
services:
  fms-mysql:
    build:
      context: ../../service/mysql/
      dockerfile: Dockerfile
    ports:
      - "3306:3306"

  fms:
    build:
      context: ../../service/fms/
      dockerfile: fms.Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - fms-mysql