// Code generated by goctl. DO NOT EDIT.
package types

type BillReq struct {
	BookId    string `form:"bookId"`
	StartedAt int64  `form:"startAt,optional"`
	EndedAt   int64  `form:"endedAt,optional"`
	PageNum   int64  `form:"pageNum,optional,default=0"`
	PageSize  int64  `form:"pageSize,optional,default=50"`
}

type Bill struct {
	Id       int     `json:"id"`
	BillType string  `json:"billType"`
	Amount   float64 `json:"amount"`
	Remark   string  `json:"remark"`
	Category int     `json:"category"`
	AssetIn  string  `json:"assetIn"`
	AssetOut string  `json:"assetOut"`
}

type BillListReply struct {
	Bills    []Bill `json:"bills"`
	PageNum  int64  `json:"pageNum"`
	PageSize int64  `json:"PageSize"`
	Count    int64  `json:"count"`
}
