// Code generated by goctl. DO NOT EDIT.
package types

type BillReq struct {
	BookId    string `form:"bookId"`
	StartedAt int64  `form:"startAt"`
	EndedAt   int64  `form:"endedAt"`
}

type Bill struct {
	Id       string `json:"id"`
	BillType string `json:"billType"`
	Amount   int    `json:"amount"`
	Remark   string `json:"remark"`
	AssetIn  string `json:"assetIn"`
	AssetOut string `json:"assetOut"`
}

type BillListReply struct {
	Bills []Bill `json:"bills"`
}
