basic:
  address: 
  port: 8080
  debug: true

log:
  # Log file path
  outputPaths:
    - stdout
    - /ism/log/fms.log
  level: debug
  # Log format, options: json, console
  encoding: json

database:
  type: postgres
  host: "fms-postgres-postgresql"
  port: 5432
  user: postgres
  dbname: postgres
  sslmode: disable