// Code generated by goctl. DO NOT EDIT!

package postgres

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	assetCategoryFieldNames          = builder.RawFieldNames(&AssetCategory{}, true)
	assetCategoryRows                = strings.Join(assetCategoryFieldNames, ",")
	assetCategoryRowsExpectAutoSet   = strings.Join(stringx.Remove(assetCategoryFieldNames, "create_time", "update_time", "create_at", "update_at"), ",")
	assetCategoryRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(assetCategoryFieldNames, "id", "create_time", "update_time", "create_at", "update_at"))
)

type (
	assetCategoryModel interface {
		Insert(ctx context.Context, data *AssetCategory) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AssetCategory, error)
		Update(ctx context.Context, data *AssetCategory) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAssetCategoryModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AssetCategory struct {
		Id        int64        `db:"id"`
		Name      string       `db:"name"`
		CreatedAt time.Time    `db:"created_at"`
		UpdatedAt sql.NullTime `db:"updated_at"`
		IsDeleted bool         `db:"is_deleted"`
	}
)

func newAssetCategoryModel(conn sqlx.SqlConn) *defaultAssetCategoryModel {
	return &defaultAssetCategoryModel{
		conn:  conn,
		table: `"public"."asset_category"`,
	}
}

func (m *defaultAssetCategoryModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAssetCategoryModel) FindOne(ctx context.Context, id int64) (*AssetCategory, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", assetCategoryRows, m.table)
	var resp AssetCategory
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAssetCategoryModel) Insert(ctx context.Context, data *AssetCategory) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, assetCategoryRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.CreatedAt, data.UpdatedAt, data.IsDeleted)
	return ret, err
}

func (m *defaultAssetCategoryModel) Update(ctx context.Context, data *AssetCategory) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, assetCategoryRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Name, data.CreatedAt, data.UpdatedAt, data.IsDeleted)
	return err
}

func (m *defaultAssetCategoryModel) tableName() string {
	return m.table
}
