// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"fms/service/fms/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/bill",
				Handler: listBillHandler(serverCtx),
			},
		},
		rest.WithPrefix("/fms"),
	)
}
